version: '3'

services:
  web:
    image: nginx:alpine
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
      - "./www:/var/www/html/app"
    ports:
      - "8005:80"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
      - cache
      - composer

  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    restart: always
    volumes:
        - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
        - "./www:/var/www/html/app"

  cache:
    image: redis:3.2-alpine
    command: ["redis-server", "--appendonly", "yes"]

  composer:
    image: composer
    volumes:
      - "./www:/app"
    command: install
